--- # roles/airflow/tasks/main.yml

- name: install apt-deps
  apt: name={{ item }} state=present update_cache=yes
  with_items: "{{ virtualenv3_dependencies }}"
  become: yes

- name: download virtualenvwrapper
  pip: name=virtualenvwrapper state=present
  become: yes

- name: update pip
  pip: name=pip state=latest
  become: yes

- name: install virtualenvwrapper
  pip: name=virtualenvwrapper state=present
  become: yes

- name: create workon home
  file: path={{ workon_home }} state=directory mode=0775
        owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
  become: yes

- name: create virtualenv
  shell: "virtualenv -p `which python3` {{ virtualenv }}"
  args:
    creates: "{{ virtualenv }}"

- name: install security packages
  pip: name={{ item }} state=latest executable={{ virtualenv_pip }}
  with_items: "{{ virtualenv3_security_requirements }}"

- name: create profile
  file: path=/home/{{ ansible_ssh_user }}/.profile state=file
        mode=0700 owner={{ ansible_ssh_user }} group={{ ansible_ssh_user }}
  become: yes

- name: set up profile to activate virtualenv on entry
  blockinfile:
    dest: /home/{{ ansible_ssh_user }}/.profile
    block: |
      export WORKON_HOME={{ workon_home }}
      source virtualenvwrapper.sh
